name: easy_audio
description: Easy record audio file, and friendly convert `speech_to_text`
version: 2.0.0
homepage: https://github.com/fighttech-vn/easy_audio

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.10.5
  audio_session: ^0.2.2
  record: 6.0.0
  path_provider: ^2.1.5
  speech_to_text: 7.0.0
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
