class RecordLanguageContants {
  static const String defaultLang = 'English (United States)';

  static const Map<String, String> languages = <String, String>{
    'Arabic (Saudi Arabia)': 'ar-SA',
    'Cantonese (China mainland)': 'yue-CN',
    'Catalan (Spain)': 'ca-ES',
    'Chinese (China mainland)': 'zh-CN',
    'Chinese (Hong Kong)': 'zh-HK',
    'Chinese (Taiwan)': 'zh-TW',
    'Croatian (Croatia)': 'hr-HR',
    'Czech (Czechia)': 'cs-CZ',
    'Danish (Denmark)': 'da-DK',
    'Dutch (Belgium)': 'nl-BE',
    'Dutch (Netherlands)': 'nl-NL',
    'English (Australia)': 'en-AU',
    'English (Canada)': 'en-CA',
    'English (India)': 'en-IN',
    'English (Indonesia)': 'en-ID',
    'English (Ireland)': 'en-IE',
    'English (New Zealand)': 'en-NZ',
    'English (Philippines)': 'en-PH',
    'English (Saudi Arabia)': 'en-SA',
    'English (Singapore)': 'en-SG',
    'English (South Africa)': 'en-ZA',
    'English (United Arab Emirates)': 'en-AE',
    'English (United Kingdom)': 'en-GB',
    'English (United States)': 'en-US',
    'English (Vietnam)': 'en-VN',
    'Finnish (Finland)': 'fi-FI',
    'French (Belgium)': 'fr-BE',
    'French (Canada)': 'fr-CA',
    'French (France)': 'fr-FR',
    'French (Switzerland)': 'fr-CH',
    'German (Austria)': 'de-AT',
    'German (Germany)': 'de-DE',
    'German (Switzerland)': 'de-CH',
    'Greek (Greece)': 'el-GR',
    'Hebrew (Israel)': 'he-IL',
    'Hindi (India)': 'hi-IN',
    'Hindi (Latin)': 'hi-Latn',
    'Hungarian (Hungary)': 'hu-HU',
    'Indonesian (Indonesia)': 'id-ID',
    'Italian (Italy)': 'it-IT',
    'Italian (Switzerland)': 'it-CH',
    'Japanese (Japan)': 'ja-JP',
    'Korean (South Korea)': 'ko-KR',
    'Malay (Malaysia)': 'ms-MY',
    'Norwegian Bokmål (Norway)': 'nb-NO',
    'Polish (Poland)': 'pl-PL',
    'Portuguese (Brazil)': 'pt-BR',
    'Portuguese (Portugal)': 'pt-PT',
    'Romanian (Romania)': 'ro-RO',
    'Russian (Russia)': 'ru-RU',
    'Shanghainese (China mainland)': 'wuu-CN',
    'Slovak (Slovakia)': 'sk-SK',
    'Spanish (Chile)': 'es-CL',
    'Spanish (Colombia)': 'es-CO',
    'Spanish (Latin America)': 'es-419',
    'Spanish (Mexico)': 'es-MX',
    'Spanish (Spain)': 'es-ES',
    'Spanish (United States)': 'es-US',
    'Swedish (Sweden)': 'sv-SE',
    'Thai (Thailand)': 'th-TH',
    'Turkish (Türkiye)': 'tr-TR',
    'Ukrainian (Ukraine)': 'uk-UA',
    'Vietnamese (Vietnam)': 'vi-VN',
  };
}
