name: Pipeline Build Verify Compile
 
on:
  workflow_dispatch:
 
jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. Test folder current
        shell: bash
        run: echo '${{env.pathProject}}'

      - name: 3. ☕️ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: 4. Build apk
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter
        working-directory: ./example
      - run: flutter build apk --debug
  
  build_ios:
    runs-on: macos-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. Test folder current
        shell: bash
        run: echo '${{env.pathProject}}'

      - name: 3. Build ios no-codesign
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter
        working-directory: ./example
      - run: flutter build ios --no-codesign
